### ISSUE TITLE
Profiling and Performance not working?

### ISSUE THREAD

**Issue by corj-aolabor** [LordSimal/cakephp-sentry#4]
Hey. I installed cakephp-sentry and the sentry sdk and it is working except the profiling and performance features. I also installed excimer as instructed.

**Comment by LordSimal** [comment]
This plugin does not (yet) support these features from the PHP Sentry SDK.

But a PR is more then welcome 😁

**Comment by corj-aolabor** [comment]
Okay. I will see if i find time until then see this as a feature request.
